# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('meta_keywords', models.CharField(max_length=255, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(max_length=255, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField()),
                ('description', models.CharField(max_length=500)),
                ('available', models.BooleanField(default=False)),
                ('picture', models.ImageField(max_length=140, upload_to=None)),
                ('sku', models.CharField(max_length=140)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_keywords', models.CharField(max_length=255, verbose_name='Meta Keywords')),
                ('meta_description', models.CharField(max_length=255, verbose_name='Meta Description')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='app.Category')),
            ],
        ),
    ]
